version: "3.9"
services:
  renta:
    build:
      context: .
    working_dir: /var/www/
    restart: always
    volumes:
      - ./app:/var/www/
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=judasz
    restart: always
    ports:
      - "3307:3306"
  nginx:
    image: nginx:1.19-alpine
    working_dir: /var/www/
    volumes:
      - ./app:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
    ports:
      - "8000:80"
    restart: always
